stages:
  - deploy

deploy-prod:
  stage: deploy
  environment:
    name: production
    url: https://phyberapex.de
  only:
    - master
  script:
    - npm i
    # your build command
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod

deploy-draft:
  stage: deploy
  environment:
    name: draft
  only:
    - devlop
  script:
    - npm i
    # your build command
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
